#!/bin/sh
python docs/generate_docs.py
git add docs/APILibraryDocumentation.html
git add docs/GUILibraryDocumentation.html
git add docs/SOAPLibraryDocumentation.html
git add docs/DesktopLibraryDocumentation.html
