categories:
  - title: '🚀 Features'
    labels: 
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'dependencies'
      - 'maintenance'
      - 'docs'
      - 'tech debt'
      - 'security fix'
      - 'security vulnerability'
template: |
  ## What’s Changed
  $CHANGES
  
