language: python
python:
  - "3.6"
branches:
  except:
    - /^(documentation).*$/i
sudo: required
dist: trusty
addons:
  chrome: stable
cache: pip
install:
  - pip install .
  - pip install python-coveralls
  - pip install pytest-cov
before_script:
  - wget "http://chromedriver.storage.googleapis.com/76.0.3809.12/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pytest --cov src -v
  - robot -e BrokenORWindows test
after_success:
  - coveralls
