name: 🐛 Bug Report
description: File a bug report
title: "[🐛 Bug]: "
labels: [bug, needs-investigation]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe clearly and concisely the bug including instructions showing how to reproduce it.
      placeholder: |
        Please add as many details as possible to avoid assumptions from our side. How do you
        trigger this bug? What did you expect to happen? Please walk us through it step by step.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted
        into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What host operating system are you using to run RobotFramework-Zoomba?
      placeholder: Windows 10? macOS BigSur? Ubuntu?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: RobotFramework-Zoomba version (tag)
      description: What version of RobotFramework-Zoomba are you using?
      placeholder: 2.13.1? Please use the full tag, avoid "latest"
    validations:
      required: true