name: Broken Links Crawler
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check_broken_links:
    runs-on: ubuntu-latest
    steps:
      - name: Check for broken links
        id: link-report
        uses: peter-evans/link-checker@v1.2.2
