name: Broken-Links-Crawler
uses: ScholliYT/Broken-Links-Crawler-Action@v2.0.0
with:
  # Which website to check
  website_url: https://accruent.github.io/robotframework-zoomba/
  # Turn verbose mode on/off
  verbose: false
