name: run-tests
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [ 3.6, 3.7, 3.8 ]
          include:
            - os: ubuntu-latest
              set_display: export DISPLAY=:99; Xvfb :99 -screen 0 1024x768x24 -ac -noreset & sleep 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install coveralls mock pytest-cov
          sudo apt-get update
          sudo apt-get -y -q install xvfb scrot zip curl libxml2-dev libxslt1-dev
      - name: Ruby dependency
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
        run: gem install coveralls-lcov
      - name: Run Unit Tests
        run: |
          pytest --cov src -v
          coveralls --output=coverage.json
          coveralls-lcov -v -n coverage.info > coverage.json
      - name: Run Robot Tests
        run: |
          ${{ matrix.set_display }}
          robot -e BrokenORWindowsORMobile test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Coveralls
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          coveralls

#      - name: Coveralls
#        uses: AndreMiras/coveralls-python-action@develop
#        with:
#          parallel: true
#          flag-name: Run Unit Tests
#          debug: true
#
#  coveralls_finish:
#    needs: run-tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Coveralls Finished
#        uses: AndreMiras/coveralls-python-action@develop
#        with:
#          parallel-finished: true
#          debug: true

