name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-tests-edge:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run Edge Robot Tests
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: robot -i Edge --output reports/outputEdge.xml test

  run-tests-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        include:
          - os: ubuntu-latest
            set_display: export DISPLAY=:99; Xvfb :99 -screen 0 1024x768x24 -ac -noreset & sleep 3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mock
          sudo apt-get update
          sudo apt-get -y -q install xvfb scrot zip curl libxml2-dev libxslt1-dev
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Run Chrome Robot Tests
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: |
            ${{ matrix.set_display }}
            robot -e BrokenORWindowsOREdge --output reports/outputChrome.xml test

  run-tests-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install coveralls mock pytest-cov
          sudo apt-get update

      - name: Run Unit Tests
        run: |
          pytest --cov-config=.coveragerc --cov=src -v

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.python-version }}
          parallel: true
        run: |
          coveralls --service=github
